service: chalana-chitra-kathalu

frameworkVersion: '3'
custom:
  serverless-offline:
    noPrependStageInUrl: true

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  #profile: TheWriter
  stage: dev
  region: ap-south-1
  environment:
  timeout: 899 #must be <= 900
  tracing:
    apiGateway: true
    lambda: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:*
            - s3:*
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
          Resource: '*'
functions:
  app:
    handler: handler.handler
    timeout: 30
    #reservedConcurrency: 100
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: '*'
            headers: '*'
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'
            headers: '*'
plugins:
  # - serverless-http
  - serverless-offline
  - serverless-dotenv-plugin
